### ISSUE TITLE
[FR] A way to include related resources with specific types

### ISSUE THREAD

**Issue by ghost** [mathematic-inc/ts-japi#17]
I probably am missing something but I'm looking forward to using `ts-japi` in a production environment and one feature I find missing is a way to optionally include specific related types.

For example a user can create articles and also like like articles. The `users` resource have two relationships - `articles` and `likes`. What I want to accomplish is to keep both `articles` and `likes` as relationships in the designated field but optionally include only `articles`. I can't seem to find a way to do so in the docs which by the way are very comprehensive. It seems to me that the `depth` setting on the `Serializer` is all-or-nothing.

Thank you for the great work!

**Comment by jrandolf** [comment]
I thought about implementing this before, but the issue arises when higher depths and multiple resource types are used. In this case, knowing the resource type to include/exclude is not enough, and one would need to know the entire resource tree in order to properly optionalize resource types. If you are looking for something like this, I recommend GraphQL. JSON:API (and almost every other standard) lacks this feature which is why GraphQL is so popular.
